networks:
  redis-net:
    driver: bridge # Testing 2

services:
  app:
    image: ghcr.io/laihantao/order-system:latest # Remove image in local, use build instead for local testing, and use image for production deployment
    build: .
    container_name: java-order-system
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis-master
    networks:
      - redis-net
      
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: order_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - redis-net

  redis-master:
    image: redis:7
    container_name: redis-master
    ports:
      - "6379:6379"
    networks:
      - redis-net
    command: >
      redis-server 
        --port 6379
        --replica-announce-ip redis-master
        --replica-announce-port 6379

  redis-replica-1:
    image: redis:7
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    networks:
      - redis-net
    depends_on:
      - redis-master
    command: >
      redis-server 
      --replicaof redis-master 6379
      --replica-announce-ip redis-replica-1
      --replica-announce-port 6379

  redis-replica-2:
    image: redis:7
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    networks:
      - redis-net
    depends_on:
      - redis-master
    command: >
      redis-server 
      --replicaof redis-master 6379
      --replica-announce-ip redis-replica-2
      --replica-announce-port 6379

  sentinel-1:
    image: redis:7
    container_name: sentinel-1
    ports:
      - "26379:26379"
    networks:
      - redis-net
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"] ## Run Redis Sentinel with the provided configuration file when the container starts
    volumes:
      - ./redis-sentinel/s1/:/etc/redis/ ## Mount from host to container

  sentinel-2:
    image: redis:7
    container_name: sentinel-2
    ports:
      - "26380:26379"
    networks:
      - redis-net
    depends_on:
      - redis-master
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./redis-sentinel/s2/:/etc/redis/

  sentinel-3:
    image: redis:7
    container_name: sentinel-3
    ports:
      - "26381:26379"
    networks:
      - redis-net
    depends_on:
      - redis-master
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./redis-sentinel/s3/:/etc/redis/